spring:
  application:
    name: booktracker-backend

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:booktracker_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:replace-it-please}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yaml

  jpa:
    show-sql: ${SHOW_SQL:false}
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 50

  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false

  jackson:
    default-property-inclusion: non_empty

  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:10MB}
      max-request-size: ${MAX_REQUEST_SIZE:30MB}

  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties.mail.smtp:
      auth: ${SMTP_ENABLE_AUTH}
      starttls:
        enable: ${SMTP_ENABLE_TLS}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}

springdoc:
  api-docs:
    enabled: ${ENABLE_API_DOCS:false}
  swagger-ui:
    enabled: ${ENABLE_SWAGGER_UI:false}

app:
  web:
    max-file-size: ${spring.servlet.multipart.max-file-size}
  minio:
    url: ${MINIO_URL:http://localhost:9000}
    user: ${MINIO_ROOT_USER:minio}
    password: ${MINIO_ROOT_PASSWORD:replace-it-please}
    url-expiry: ${MINIO_URL_EXPIRY:1h}
    buckets:
      covers: ${MINIO_COVERS_BUCKET:covers}
  image:
    target-format: ${IMAGE_TARGET_FORMAT:webp}
    quality: ${IMAGE_QUALITY:0.8}
    max-width: ${IMAGE_MAX_WIDTH:1080}
    max-height: ${IMAGE_MAX_HEIGHT:1080}
  argon2:
    salt-length: ${ARGON2_SALT_LENGTH:16}
    hash-length: ${ARGON2_HASH_LENGTH:32}
    parallelism: ${ARGON2_PARALLELISM:1}
    memory: ${ARGON2_MEMORY:16384}
    iterations: ${ARGON2_ITERATIONS:2}
  otp:
    length: ${OTP_CODE_LENGTH:6}
    expiry: ${OTP_CODE_EXPIRY:10m}
  smtp:
    from: ${spring.mail.username}
  jwt:
    secret: ${JWT_SECRET}
  auth:
    token:
      access-expiry: ${AUTH_ACCESS_TOKEN_EXPIRY:10m}
      refresh-expiry: ${AUTH_REFRESH_TOKEN_EXPIRY:30d}
      issuer: ${AUTH_TOKEN_ISSUER}
  redis:
    ttl: ${REDIS_TTL:24h}
  external:
    google-books:
      base-url: ${GOOGLE_BOOKS_BASE_URL:https://www.googleapis.com/books/v1}
      api-key: ${GOOGLE_BOOKS_API_KEY}
  rate-limit:
    capacity: ${RATE_LIMIT_CAPACITY:10}
    refill-amount: ${RATE_LIMIT_REFILL_AMOUNT:10}
    refill-duration: ${RATE_LIMIT_REFILL_DURATION:1m}