spring:
  application:
    name: booktracker-backend

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:booktracker_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:replace-it-please}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
