spring:
  application:
    name: booktracker-backend

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:booktracker_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:replace-it-please}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 50

  sql:
    init:
      mode: always
      schema-locations: file:./database-init/1-schema.sql
      data-locations: file:./database-init/2-schema-data.sql

  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false

  servlet:
    multipart:
      max-file-size: 10MB

app:
  storage:
    covers-path: "storage/covers"